"""Mission-neutral SAR processing domain contracts."""

from .backends import ArrayReader, ArrayWriter
from .contracts import (
    ArrayDescriptor,
    ArrayRepresentation,
    CalibrationState,
    CarrierState,
    ComplexInterferogram,
    CoregistrationState,
    FlatteningState,
    OrbitMetadata,
    OrbitStateVector,
    PairProduct,
    SLCProduct,
    StackProduct,
    UnwrapResult,
)
from .coordinates import (
    CoordinateSystem,
    GeoGrid,
    OffsetField,
    RadarGrid,
    TransformDirection,
    TransformLUT,
)
from .errors import (
    GridMismatchError,
    InvalidProcessingStateError,
    PairConfigurationMigrationError,
    ProcessingContractError,
)
from .provenance import ProcessingEvent, ProvenanceRecord, SoftwareIdentity
from .readers import (
    DopplerCentroidPolynomial,
    MissingCriticalMetadataError,
    SLCReader,
    SLCReadResult,
    ValidSampleMask,
    require_critical_metadata,
)
from .resampling import lanczos_resample
from .resources import (
    ProcessTreeAdmission,
    ProcessTreeMemoryWatchdog,
    ProcessTreeSampler,
    ProcessTreeSamplingError,
    ProcessTreeSnapshot,
    ResourceAdmissionError,
    ResourceAdmissionLedger,
    ResourceBudget,
    ResourceReservation,
    ResourceUsage,
    bootstrap_worker_runtime,
)
from .source_snapshots import (
    ImmutableSourceSnapshot,
    SourceSnapshotEntry,
    snapshot_local_source,
)
from .storage import ChunkAccessLog, ChunkedZarrArrayStore, InMemoryArrayStore
from .synthetic_slc import SyntheticSLCReader, SyntheticSLCSpec, write_synthetic_slc

__all__ = [
    "ArrayDescriptor",
    "ArrayReader",
    "ArrayRepresentation",
    "ArrayWriter",
    "CalibrationState",
    "CarrierState",
    "ChunkAccessLog",
    "ChunkedZarrArrayStore",
    "ComplexInterferogram",
    "CoordinateSystem",
    "CoregistrationState",
    "DopplerCentroidPolynomial",
    "FlatteningState",
    "GeoGrid",
    "GridMismatchError",
    "ImmutableSourceSnapshot",
    "InMemoryArrayStore",
    "InvalidProcessingStateError",
    "MissingCriticalMetadataError",
    "OffsetField",
    "OrbitMetadata",
    "OrbitStateVector",
    "PairConfigurationMigrationError",
    "PairProduct",
    "ProcessTreeAdmission",
    "ProcessTreeMemoryWatchdog",
    "ProcessTreeSampler",
    "ProcessTreeSamplingError",
    "ProcessTreeSnapshot",
    "ProcessingContractError",
    "ProcessingEvent",
    "ProvenanceRecord",
    "RadarGrid",
    "ResourceAdmissionError",
    "ResourceAdmissionLedger",
    "ResourceBudget",
    "ResourceReservation",
    "ResourceUsage",
    "SLCProduct",
    "SLCReadResult",
    "SLCReader",
    "SoftwareIdentity",
    "SourceSnapshotEntry",
    "StackProduct",
    "SyntheticSLCReader",
    "SyntheticSLCSpec",
    "TransformDirection",
    "TransformLUT",
    "UnwrapResult",
    "ValidSampleMask",
    "bootstrap_worker_runtime",
    "lanczos_resample",
    "require_critical_metadata",
    "snapshot_local_source",
    "write_synthetic_slc",
]
