"""Product contracts and stage tokens for the processing spine."""

from __future__ import annotations

from faninsar.processing.contracts.ifg import Interferogram, InterferogramStack
from faninsar.processing.contracts.prepared_geometry import (
    ActivationToken,
    AppliedSolution,
    CoregistrationPolicy,
    GeometricPhase,
    PairResidualSolution,
    PhaseCarrier,
    PhaseState,
    PreparedGeometryArrayPayload,
    PreparedGeometryProvider,
    PreparedIdentity,
    PreparedLutArrayPayload,
    PreparedLutHandle,
    ProviderLeaseToken,
    ProviderQualificationReceipt,
    ResidualObservation,
    ResidualSolution,
    ResidualStatus,
    ResourceLimits,
    SceneViewRequest,
    SourceDescriptor,
    SourceRole,
    StackActivationBinding,
    WorkerAttestation,
    geo_grid_identity,
    get_neutral_identity_projector,
)
from faninsar.processing.contracts.products import (
    ArrayDescriptor,
    ArrayRepresentation,
    CalibrationState,
    CarrierState,
    ComplexInterferogram,
    CoregistrationState,
    FlatteningState,
    OrbitMetadata,
    OrbitStateVector,
    PairProduct,
    SLCProduct,
    StackProduct,
    UnwrapResult,
)
from faninsar.processing.contracts.stage import Stage, StageNode
from faninsar.processing.contracts.tokens import ArrayToken, assert_token

__all__ = [
    "ActivationToken",
    "AppliedSolution",
    "ArrayDescriptor",
    "ArrayRepresentation",
    "ArrayToken",
    "CalibrationState",
    "CarrierState",
    "ComplexInterferogram",
    "CoregistrationPolicy",
    "CoregistrationState",
    "FlatteningState",
    "GeometricPhase",
    "Interferogram",
    "InterferogramStack",
    "OrbitMetadata",
    "OrbitStateVector",
    "PairProduct",
    "PairResidualSolution",
    "PhaseCarrier",
    "PhaseState",
    "PreparedGeometryArrayPayload",
    "PreparedGeometryProvider",
    "PreparedIdentity",
    "PreparedLutArrayPayload",
    "PreparedLutHandle",
    "ProviderLeaseToken",
    "ProviderQualificationReceipt",
    "ResidualObservation",
    "ResidualSolution",
    "ResidualStatus",
    "ResourceLimits",
    "SLCProduct",
    "SceneViewRequest",
    "SourceDescriptor",
    "SourceRole",
    "StackActivationBinding",
    "StackProduct",
    "Stage",
    "StageNode",
    "UnwrapResult",
    "WorkerAttestation",
    "assert_token",
    "geo_grid_identity",
    "get_neutral_identity_projector",
]
